language: node_js
node_js:
- 10.16.0
cache:
  directories:
  - node_modules
install:
- npm install
before_script: 

script:
- npm run build

after_script:
- rf -rf .git
- cd ./.docz/dist
- git init
- git config user.name "${U_NAME}"
- git config user.email "${U_EMAIL}"
- git add .
- git commit -m "Update version"
- git remote add origin "https://${GH_TOKEN}@${GH_REF}"
- git push --force --quiet

branches:
  only:
  - master
